name: Publish Alpha

on:
  push:
    tags:
      - "*alpha**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get date
        run: echo "DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Set Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
      - name: Set Minecraft Version
        run: echo "MINECRAFT_VERSION=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
      - name: Build jar
        run: ./gradlew build
        env:
          BUILD_SNAPSHOT: false
          BUILD_ID: ${{env.RELEASE_VERSION}}
      - name: Upload assets to GitHub
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: Alpha Release ${{env.MINECRAFT_VERSION}}-${{env.RELEASE_VERSION}}
          files: |
            build/libs/*